c_compiler_version:
  - 9

cxx_compiler_version:
  - 9

cuda_compiler:
  - nvcc

cmake_version:
  - ">=3.23.1,!=3.25.0"

fmt_version:
  - ">=9.1.0"

gtest_version:
  - "=1.10.0"

spdlog_version:
  - ">=1.11.0"

sysroot_version:
  - "2.17"
