c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - nvcc

cmake_version:
  - ">=3.23.1,!=3.25.0"

fmt_version:
  - ">=9.1.0,<10"

gtest_version:
  - ">=1.13.0"

spdlog_version:
  - ">=1.11.0,<1.12"

sysroot_version:
  - "2.17"
