name: RMM wheels

on:
  push:
    branches:
      - 'pull-request/[0-9]+'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  rmm-wheels:
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-manylinux.yml@feat/wheel-ci-actions-2
    with:
      package-dir: python
      package-name: "rmm"
      python-package-versioneer-override: "22.10.00a"
      python-version: "3.8 3.9"
      python-package-build-tag: "4"

      manylinux-container-amd64: "rapidsai/manylinux2014"
      manylinux-container-arm64: "rapidsai/manylinux_2_31"

      auditwheel-repair-command-amd64: "auditwheel --verbose repair -w {dest_dir} --plat manylinux_2_17_x86_64 {wheel}"
      auditwheel-repair-command-arm64: "auditwheel --verbose repair -w {dest_dir} --plat manylinux_2_24_aarch64 {wheel}"

      test-container-amd64: "rapidsai/manylinux_2_27" # use the 18.04 container to test wheels on an old-ish distro
      test-container-arm64: "rapidsai/manylinux_2_27"
      test-extras: "test"
      test-unittest: "python -m py.test -v ./python/rmm/tests"
      test-smoketest: "import rmm; buf = rmm.DeviceBuffer(size=100); print(buf.size); print(buf.ptr); assert buf.size == 100"
    secrets: inherit
